update-bootstrap: add rust tools

diff --git a/util/update-bootstrap b/util/update-bootstrap
--- a/util/update-bootstrap
+++ b/util/update-bootstrap
@@ -15,15 +15,22 @@ unsquashfs /mnt/archiso/x86_64/airootfs.sfs
 
 install_binary_with_libraries() {
   if [ ! -x "`which $1`" ]; then
-    echo "Please install $1"
+    prog=$2
+    if [ "$prog" = "" ]; then
+      prog=$1
+    fi
+    echo "Binary \`$1\` not found, please install package \`$prog\`"
     exit 1
   fi
 
   err=0
   for lib in $(ldd $(which $1) | grep '=>' | sed -r 's/.*?=> (.*?) \(.*/\1/'); do
+    if [ "$lib" = "linux-vdso.so.1" ]; then
+      continue
+    fi
     if [ ! -f "squashfs-root$lib" ]; then
-      echo "Library $lib required by $1 but not available on live system"
-      err=1
+      echo "Library $lib required by $1 but not available on live system, copying..."
+      cp "$lib" "squashfs-root$lib" || (echo "copying failed"; err=1)
     fi
   done
   if [ "$err" = 1 ]; then
@@ -34,8 +41,8 @@ install_binary_with_libraries() {
 }
 
 install_binary_with_libraries mprime
-install_binary_with_libraries sedutil-cli
-install_binary_with_libraries linuxpba
+install_binary_with_libraries sedutil-cli sedutil
+install_binary_with_libraries linuxpba sedutil
 
 cp $(eval echo ~`logname`)/dotfiles/xorg/{.xinitrc,.Xresources} squashfs-root/root/
 
@@ -50,7 +57,8 @@ pacman-key --refresh-keys
 pacman -Sy --noconfirm
 pacman -S --noconfirm archlinux-keyring
 pacman -Syu --noconfirm
-pacman -S --noconfirm --needed xorg-server xorg-xinit xorg-apps xf86-video-intel gparted kdiskmark rxvt-unicode
+pacman -S --noconfirm --needed xorg-server xorg-xinit xorg-apps xf86-video-intel gparted kdiskmark rxvt-unicode wget rustup git curl
+rustup install stable nightly
 # fix compinit directories
 chown -R root:root /usr/share/zsh
 chmod -R 755 /usr/share/zsh
